data<-read.csv("household_power_consumption.txt", sep = ";", na.strings="?")
data<-subset(data, Date %in% c("1/2/2007" ,"2/2/2007"))
data$ts<-strptime(paste(data$Date, data$Time),"%d/%m/%Y %H:%M:%S")
par(mfrow=c(1,1))
with(data, plot(ts,Global_active_power,type = "line", xlab="", ylab="Global Active Power (kilowatts)"))
dev.copy(png,"plot2.png", width=480, height=480)
dev.off()
