data<-read.csv("household_power_consumption.txt", sep = ";", na.strings="?")
data<-subset(data, Date %in% c("1/2/2007" ,"2/2/2007"))
data$ts<-strptime(paste(data$Date, data$Time),"%d/%m/%Y %H:%M:%S")
par(mfrow=c(1,1))
with(data, plot(ts,Sub_metering_1, type = "line", xlab="", ylab="Energy sub metering"))
with(data, lines(ts,Sub_metering_2,type = "line", col="red"))
with(data, lines(ts,Sub_metering_3,type = "line", col="blue"))
legend("topright", lty=1, cex=0.8, legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black", "red","blue"))
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()
